title: Mileniálové
baseURL: /
params:
  accent_color: pink
  color_scheme: light
  footer:
    content: >-
      &copy; 2019 Mileniálové s.r.o. <br /> Firma je zapsaná v OR u Městského
      soudu v Praze, oddíl C, vložka 313739 <br />IČ: 08167184 <br /> DIČ:
      CZ08167184
    has_social: true
    links: []
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
DefaultContentLanguage: cs
languages:
  cs:
    languageName: CZ
    weight: 1
    params:
      header:
        has_nav: true
        title: Mileniálové s.r.o.
  en:
    languageName: EN
    weight: 2
    params:
      header:
        has_nav: true
        title: test en
      footer: 
        content: >-
          &copy; 2019 Mileniálové s.r.o. <br />
          Company registration number (IČ): 08167184
        has_social: true

  