title: Mileniálové
baseURL: /
params:
  accent_color: pink
  color_scheme: light
  footer:
    content: '&copy; 2019 Mileniálové s.r.o. '
    has_social: true
    links: []
  header:
    has_nav: true
    title: Mileniálové s.r.o.
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
