title: Mileniálové
baseURL: /
params:
  accent_color: pink
  color_scheme: light
  footer:
    content: >-
      &copy; {{ .Now.Year }} Mileniálové s.r.o. <br /> Firma je zapsaná v OR u
      Městského soudu v Praze, oddíl C, vložka 313739 <br />IČ: 08167184 <br />
      DIČ: CZ08167184
    has_social: true
    links: []
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
